version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pure-trading-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pure-trading-network

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile.ingestion
    container_name: pure-trading-ingestion
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pure-trading-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: pure-trading-api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pure-trading-network

  web:
    image: node:20-alpine
    container_name: pure-trading-web
    working_dir: /app
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - pure-trading-network

volumes:
  postgres_data:

networks:
  pure-trading-network:
    driver: bridge
