app = "pure-analytics-api"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.api"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[processes]
  app = "/app/api"
  ingestion = "/app/ingestion"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  processes = ["ingestion"]
